#!/usr/bin/env bash

. /home/hackia/woman/woman_utils

woman_generate_tools

case "$1" in
tree)
  if [[ -n "$2" ]]; then
    woman_tree_group "$2"
  else
    woman_tree
  fi
  ;;
ssh)
  woman_ssh "$2"
  exit 0
            ;;

l | language)
  select_lang "$2"
  ;;

status)
  woman_debug_all
  ;;

run)
  woman_run "$2"
  ;;
url)
  case "$2" in
  add) woman_url_add "$3" "$4" ;;
  update) woman_url_update "$3" "$4" ;;
  rm) woman_url_rm "$3" ;;
  list) woman_url_list ;;
  get) woman_url_get "$3" ;;
  *) echo "Utilisation : woman url [add|update|rm|get|list] <outil> [url]" ;;
  esac
  ;;
stop)
  stop_sessions
  ;;
start)
  start_group "$@"
  ;;
help | --help | -h | "")
  echo
  echo
  echo "  Commandes disponibles :"
  echo "  woman tree             → Affiche tous les groupes et leurs outils"
  echo "  woman tree <groupe>    → Affiche uniquement un groupe"
  echo "  woman l <lang>         → Sélectionne une configuration de langage"
  echo "  woman run <outil>      → Lance un outil spécifique"
  echo "  woman list             → Liste tous les outils et ports"
  echo "  woman help             → Affiche cette aide"
  echo "  woman status           → Affiche le status des outils"
  echo "  woman auth [setup|change|show|disable]           → Affiche le status des outils"
  echo
  echo
  ;;
auth)
  case "$2" in

  setup) woman_auth_setup ;;
  change) woman_auth_change ;;
  show) woman_auth_show ;;
  disable) woman_auth_disable ;;
  login) woman_auth_login ;;
  reinstall) woman_auth_reinstall ;;
  help | --help | -h | "")
    echo
    echo
    echo "woman auth setup     → Configure l'authentification chiffrée (GPG)"
    echo "woman auth reinstall → Supprime et recrée l’authentification chiffrée"
    echo "woman auth change    → Change les identifiants chiffrés"
    echo "woman auth show      → Affiche le mode actif"
    echo "woman auth disable   → Supprime la protection"
    echo "woman auth login     → Affiche les identifiants actuels (décryptés)"
    echo
    echo
    ;;
  *)
    ko_msg "Commande invalide"
    echo
    exit 0
    ;;
  esac
  ;;
esac
